### ISSUE TITLE
UI/UX: Search Bar - Locked Frame Too Large 

### ISSUE THREAD

**Issue by nthopinion** [nthopinion/covid19#13]
Shrinking the margins of the iFrame(?) around the search bar. 

As you'll notice from this image, the box can fit about three search bars in it, taking up precious screen real estate on mobile for the physicians as they scroll: 
![image](https://user-images.githubusercontent.com/62161323/76919690-d82dad80-6886-11ea-965d-7c507ac41aca.png)

Consideration: There used to be a mail form (mailchimp) iFrame embedded that has since been removed. This large white box may also be a remnant of that... TBD

Thanks!

**Comment by rkchee** [comment]
Hi Avaskar, this is interesting.  I wondering why this occurs. Is it just a div somewhere?

**Comment by aviskarkc10** [comment]
@rkchee i am not really sure about this, but looks like it's fixed now. I will close this issue.
