### ISSUE TITLE
UI/UX: Social Buttons - Shrinking, colour coordinating, simple and streamlined

### ISSUE THREAD

**Issue by nthopinion** [nthopinion/covid19#14]
There have been requests to replace these buttons with small 'icon-only' bird/heart/flag and remove the large bulky rectangular buttons. 

Also:
- smaller
- colour = simple black (would be easier on the eyes as physician's open and close the app frequently in front of patients for reference.

See here: 
![image](https://user-images.githubusercontent.com/62161323/76919867-5ab66d00-6887-11ea-9e63-a1c223a32868.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/6nBwWlVF) by [Unito](https://www.unito.io/learn-more)

**Comment by Jennything** [comment]
Suggestions from the UX/UI team:
![Screen Shot 2020-03-19 at 6 44 17 PM](https://user-images.githubusercontent.com/56145322/77129598-dcd29d00-6a11-11ea-97f4-489f771f96a8.png)

On click:
![Screen Shot 2020-03-19 at 6 44 20 PM](https://user-images.githubusercontent.com/56145322/77129642-f4aa2100-6a11-11ea-8474-faa34cccf617.png)

the third icon (aka 'Share' icon) on click:
![Screen Shot 2020-03-19 at 6 44 46 PM](https://user-images.githubusercontent.com/56145322/77129655-0390d380-6a12-11ea-87b1-1cfe9f0acbb4.png)

Please refer to https://www.figma.com/file/kqWIqq3sxbEm8jN3scQzHz/Hacking-COVID-19?node-id=94%3A1035 for details about icons/colors/CSS style

**Comment by christianlomboy** [comment]
Hi, I can begin working on this

**Comment by aviskarkc10** [comment]
Awesome @christianlomboy

**Comment by christianlomboy** [comment]
![Apr-15-2020 19-59-40](https://user-images.githubusercontent.com/31413055/79400505-68c5df00-7f54-11ea-90b7-98a2e5cca4e0.gif)

Progress as of 4/15,
Flag button now functions properly: Now only changes color to red when user confirms they'd like to report a question - and stays red if user reports another question.

**Comment by christianlomboy** [comment]
![animation](https://user-images.githubusercontent.com/31413055/79517996-d984fe00-801d-11ea-8234-9365ee366282.gif)
PR [https://github.com/nthopinion/covid19/pull/133](https://github.com/nthopinion/covid19/pull/133) introduces color changing animations. Also refactors some CSS styling and class names.
