### ISSUE TITLE
Add a telephone icon button next to the Flag/Social Media button (that links to televideo)

### ISSUE THREAD

**Issue by raynman1** [nthopinion/covid19#178]
The button links to: https://ai-passion.appspot.com/

**Telephone Icon:** 
![image](https://user-images.githubusercontent.com/30793935/79806419-34b83880-831d-11ea-8b7d-3fd11e00a120.png)

![image](https://user-images.githubusercontent.com/30793935/79806402-2bc76700-831d-11ea-91dc-b7edc17ccaa9.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/0iXGvPgR) by [Unito](https://www.unito.io/learn-more)

**Comment by christianlomboy** [comment]
Hi, I can have this task assigned to me.

**Comment by raynman1** [comment]
Thanks Christian! This is the next step. Our doctors already have peer to peer (physician to physician) televideo live in production this morning!

**Comment by christianlomboy** [comment]
Sure! PR created https://github.com/nthopinion/covid19/pull/183 @raynman1

**Comment by gitjul** [comment]
Hi! Looks like this issue can be closed. 

A cool Github feature is that if you include `Fixes #178` in the PR description the issue will be closed automatically when the PR is merged. Can be a commit too, including the merge commit.

Any of the following keywords will work: close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved.

https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by christianlomboy** [comment]
@gitjul Great tip, thank you so much!
