### ISSUE TITLE
Q&A Listing: Create hyperlink when physician adds an answer with URL

### ISSUE THREAD

**Issue by sjohnson620** [nthopinion/covid19#21]
**Use Case:** 
Physicians may add URLs to answer section. These URLs should appear as hyperlinks to the user.

**Requirements**
-Formatting of link should be user friendly (i.e. no need to copy and paste)
-Formatting of link should match #24 

**Example:**
User inputs the following in answer section: "For the best Q&A on COVID, access http://covid19webapp.com".

Answer should display link in manner similar to below so users can easily recognize the link.

![image](https://user-images.githubusercontent.com/62316151/76929002-0c1dc880-68b1-11ea-8cbe-25e86c77be41.png)

**Comment by aviskarkc10** [comment]
Closing this as it has been implemented
