### ISSUE TITLE
Q&A Listing: Correlate answer with the physician who answered the question

### ISSUE THREAD

**Issue by sjohnson620** [nthopinion/covid19#22]
**User Story:**
As a user of the Q&A site, I may want to know the physician's name to confirm the source is reputable. As a physician user, I may want to attempt to reach out to physician who answered for more insight on a similar case or issue.

**Requirements:**
Add the following to post (need to confirm field availability):
- Physician Name (Only if physician has indicated they would like their name displayed. Regardless of name being displayed in QnA site, this information should be tracked in DB)
- Posted Date:
- Edited Date:
- Physician Location:

**Example**
![image](https://user-images.githubusercontent.com/62316151/76930334-3de45e80-68b4-11ea-8ae3-e6a84337326e.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/OBDdsNEz) by [Unito](https://www.unito.io/learn-more)

**Comment by sjohnson620** [comment]
Need to understand: Does physician login capture location? And do we capture the date the answer was posted and edited (if applicable)?

**Comment by stevenliriano** [comment]
I plan on working on this now, could this task be assigned to me and its status updated to be "in progress?"

**Comment by aviskarkc10** [comment]
@stevenliriano this is part of a bigger issue where we handle multiple answers for the same question.

Some of this has already been done, while some tasks are remaining for that feature. If you are on our slack channel, please message me so I can brief you on what is pending. And you can take that up.
