### ISSUE TITLE
Q&A Listing: Separate answers from individual physicians

### ISSUE THREAD

**Issue by sjohnson620** [nthopinion/covid19#23]
**User Story:**
Physician's may have different opinions on topics, or may have experienced different results on a case they've worked. Separating the answers will help users understand the answers are coming from multiple physicians. 

**Requirements:**
-Separate posts by author
-List author name, posted date, edited date, location (See #22 #20 )
-Like, Tweet, and Report button should appear for each answer submitted

**Example:**
![image](https://user-images.githubusercontent.com/62316151/76931821-85201e80-68b7-11ea-97c3-41b4f8a82cd7.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/yVWd655P) by [Unito](https://www.unito.io/learn-more)

**Comment by sjohnson620** [comment]
@rkchee- Can you confirm that this is what the ask was before anybody picks this up?

**Comment by nthopinion** [comment]
Hi nnation I have called a 4 pm Pacfic soom meeting to discuss the data structure change. Please join.
