### ISSUE TITLE
Q&A Listing: Improve view of sources in UI

### ISSUE THREAD

**Issue by sjohnson620** [nthopinion/covid19#24]
**User Story:**
User needs to be able to understand when there is a source on the answer and that they are able to navigate away from the page for more information. Currently sources only read "Source" which may mislead the user. 

**Requirements:** 
-Show sources in a more user friendly manner.
-Link format should match link format of #21 

**Example:**
![image](https://user-images.githubusercontent.com/62316151/76932372-c533d100-68b8-11ea-83c0-a3feb7e846ef.png)

**Comment by sjohnson620** [comment]
@rkchee Please confirm this captures the ask before it's picked up by dev.

**Comment by aviskarkc10** [comment]
This has been fixed. @sjohnson620 I will leave it up to you to close this one
