### ISSUE TITLE
Logo not working from ask a question page

### ISSUE THREAD

**Issue by SarithaPrakash** [nthopinion/covid19#242]
https://qna.askco19.com/
From this page, not able to navigate to home page on clicking the logo.
Expected page to navigate : https://www.askco19.com/
<img width="798" alt="Logo" src="https://user-images.githubusercontent.com/64408977/80363578-0cdb4e80-88a2-11ea-81e3-75e3a1241e40.PNG">

Now when click on logo, nothing happens

**Comment by gitjul** [comment]
@aviskarkc10 could you close this issue? I believe @cnagadya took care of it.
