### ISSUE TITLE
UI/UX Search Bar

### ISSUE THREAD

**Issue by rkchee** [nthopinion/covid19#43]
The search bar should clear after the patient presses enter and is satified with submission of question

┆Issue is synchronized with this [Trello card](https://trello.com/c/bin5uEFo) by [Unito](https://www.unito.io/learn-more)

**Comment by sjohnson620** [comment]
Adding more detail- can we make it clear to user that they need to attempt to search before asking a question? 

- Change default phrase on search bar to say something like "Have a question? Type here to search".
-When user attempts to search without results, change "No results found." to reflect something like "No results found. Select Ask a Question to Continue"
- **Nice to have:** Hide "Ask a Question" button upon first accessing page- reveal button once user has attempted to search. Note: Need to also make sure the logic is NOT dependent on "No Results Found..." not appearing.
-Move ask a question next to Search bar.

**Comment by aviskarkc10** [comment]
```
Nice to have: Hide "Ask a Question" button upon first accessing page- reveal button once user has attempted to search. Note: Need to also make sure the logic is NOT dependent on "No Results Found..." not appearing.
```

I'd disagree with this one @sjohnson620. I think this would confuse users.

**Comment by sjohnson620** [comment]
My concern is managing duplicates. I've already seen a few in the chat and don't want to waste doctors' time. If we can manage duplicates in another way, then I'm okay with that. I'll create an issue and try to think through it.

**Comment by aviskarkc10** [comment]
Maybe when users ask new questions, we can help identify duplicate questions? because even hiding the `Ask a Question` button until the search field has been focused won't stop from duplicate questions being created.

**Comment by rkchee** [comment]
Duplicate questions are ok for now but UX team needs to continue to evolve the search bar vs ask button .   Good so far but patients will need it simpler all the time

**Comment by fapapa** [comment]
I am going to grab this issue, if that's okay.

**Comment by fapapa** [comment]
Also a good solution to the *nice to have* discussion above is that we put "Have a question? Type here to search or ask." for the search bar, and display the *Ask a question* button _inside_ of the search results, when no results are found.

**Comment by aviskarkc10** [comment]
Hi @fapapa. Sorry you had to waste your effort here but this issue was already taken and a PR was there.

**Comment by gitjul** [comment]
@aviskarkc10 can this be closed? if so, plz do (:
