### ISSUE TITLE
The ask a question pop up is stuck

### ISSUE THREAD

**Issue by rkchee** [nthopinion/covid19#54]
It does not close after submit and we do not know if it submits.  May need to reduce pop ups and consider UX review

┆Issue is synchronized with this [Trello card](https://trello.com/c/WEkGCrsl) by [Unito](https://www.unito.io/learn-more)

**Comment by cnagadya** [comment]
Seems this is no longer the case. The pop up closes on submit and a success notification is displayed at the top right corner

**Comment by rkchee** [comment]
I think this is good news.
