### ISSUE TITLE
Newer questions should be displayed first for visitors

### ISSUE THREAD

**Issue by struanwood** [nthopinion/covid19#6]
Visitors should be presented with questions in order of how recently they were added.

**Comment by modond** [comment]
Where can I find the stream from the database? I would suggest to filter on timestamp of last mutation and add last first..?

**Comment by sherylj** [comment]
Looks like this was done in this PR : https://github.com/nthopinion/covid19/pull/10 ?

**Comment by aviskarkc10** [comment]
Yes. This issue can be closed. It has already been fixed.

**Comment by aviskarkc10** [comment]
Closing as it has been implemented
