### ISSUE TITLE
Mac/Chrome: App is Flagged as Not Secure

### ISSUE THREAD

**Issue by sjohnson620** [nthopinion/covid19#67]
**Reported bug:**
Chrome(v80.0.3987.147 64-bit) is flagging site as not secure due to adobe flash set to “ask”. Dave is navigating this site using his Mac- this is occurring in production environment.

Reported by Dave Bates

![Covid19webapp com 23Mar2020Chrome](https://user-images.githubusercontent.com/62316151/77379558-fee85a00-6d46-11ea-8fc2-75a07f8b9113.png)

**Comment by sjohnson620** [comment]
This appears to be an issue with old url certificate. New url certificate working as expected. Confirming with team if we're concerned with the old link not having a cert.

**Comment by IbbyBenali** [comment]
It looks like a certificate issue to me. Are you using Letsencrypt and autorenewing certificates? :)

**Comment by sjohnson620** [comment]
Closing issue- user who reported just needed to clear cache I believe :)
