### ISSUE TITLE
Do not display `show more` text if there is no content to show

### ISSUE THREAD

**Issue by aviskarkc10** [nthopinion/covid19#79]
Right now we have a `show more` and `show less` text on answers. But these text are displayed even if the answers are short and don't need to be expanded.

It would be good if we could remove those if the answer is already short.

![Peek 2020-03-25 19-09](https://user-images.githubusercontent.com/13309631/77541067-41876f00-6ecc-11ea-825e-2d1e87031bd6.gif)

**Comment by sndsabin** [comment]
will work on this :)
