### ISSUE TITLE
Disappeared - Confirmation Message upon Question Submission

### ISSUE THREAD

**Issue by EpicPandemonium** [nthopinion/covid19#94]
Expected result - Confirmation message upon submitting question.
Actual result - No confirmation message, potentially resulting in multiple submissions if submitter keeps pressing the "Submit" button to try to get a confirmation message.

From Serena Gerber (Writing/Marketing/PR):

"Hey guys, hopefully this is the right place to share this: I just wrote a question on askco19.com and pressed "Submit" and it didn't give me ANY confirmation at all that the question had been submitted. I pressed "Submit" a few times, so i may have even ended up submitting the question multiple times. Anyways, just wanted to let you know that it seems like the confirmation message that was appearing in the top right corner before (the message that was hard to see) is no longer visible at all. The screenshot below is after i submitted the message."
![image](https://user-images.githubusercontent.com/63129310/78410304-5ac8b200-7668-11ea-83dd-d397f457c25d.png)

**Comment by aviskarkc10** [comment]
Thanks for creating the issue. I will look at it.
